# Generated by Django 3.1.5 on 2021-01-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210125_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='label_url',
            new_name='image_url',
        ),
    ]
