# Generated by Django 3.1.5 on 2021-02-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_paring_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrialproductinfo',
            name='volume_by_packing',
            field=models.CharField(max_length=45),
        ),
    ]
