# Generated by Django 3.1.5 on 2021-02-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210201_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkdetailvolume',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
