# Generated by Django 3.1.5 on 2021-02-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210202_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrialproductinfo',
            name='label_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
