# Generated by Django 3.1.5 on 2021-02-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_industrialproductinfo_label_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkdetail',
            name='alcohol_content',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
